apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-configmap
data:
{{- if hasKey .Values.config "file_pattern" }}
{{ (.Files.Glob .Values.config.file_pattern ).AsConfig | indent 2 }}
{{- end }}
