apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-template
  labels:
    app: phoenix-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-template
  template:
    metadata:
      labels:
        app: phoenix-template
    spec:
      volumes:
        - name: rules-volume
          configMap:
            name: phoenix-configmap
      containers:
      - name: phoenix-template
        image:  gcr.io/devops-273716/gitlab/fraud-phoenix-service:fd-1069
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - mountPath: /config/rules
            name: rules-volume
            readOnly: true
        env:
          - name: RULES_FOLDER
            value: "/config/rules"