apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-template
  labels:
    app: phoenix-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-template
  template:
    metadata:
      labels:
        app: phoenix-template
    spec:
      volumes:
        - name: rules-volume
          configMap:
            name: phoenix-configmap
      containers:
      - name: phoenix-template
        image:  docker.io/aomalov/sample-akka-http:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /config/rules
            name: rules-volume
            readOnly: true
        env:
          - name: RULES_FOLDER
            value: "/config/rules"
          - name: SERVICE_PATH
            value: "fraud-service"