apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phoenix-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set_by_lua_block $res {
        local h  = ngx.req.raw_header(true)
        local newstr, n, err = ngx.re.gsub(h, "(:.*\r\n)", ",", "imJ")
        local newstr2, n, err = ngx.re.gsub(newstr, "(\r\n)", "", "imJ")
        return newstr2
      }
      proxy_set_header proxied $res;
spec:
  ingressClassName:
  rules:
    - host: fraud.gcpd-phx.doubleverify.io
      http:
        paths:
          - path: /fraud-service-nginx
            backend:
              serviceName: phoenix-template
              servicePort: 8080