apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phoenix-ingress
spec:
  ingressClassName: ngnix
  rules:
    - host: phoenix.svc
      http:
        paths:
          - path: /do_work
            backend:
              serviceName: phoenix-template
              servicePort: 8080