apiVersion: v1
kind: PersistentVolume
metadata:
  name: phoenix-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/Users/andrewm/mnt/data"