apiVersion: v1
kind: Service
metadata:
  name: phoenix-template
  labels:
    app: phoenix-template
spec:
  type: NodePort
  selector:
    app: phoenix-template
  ports:
  - name:       web
    port:       8080
    targetPort: 8080
  - name:       metrics
    port:       9095
    targetPort: 9095