apiVersion: v1
kind: Service
metadata:
  name: phoenix-template
  labels:
    app: phoenix-template
spec:
  selector:
    app: phoenix-template
  ports:
  - name:       web
    protocol: TCP
    port:       8080
    targetPort: 8080